package:
  name: pycvc
  version: "0.3.0"

source:
  git_url: https://github.com/Geosyntec/pycvc.git
  git_tag: v0.3.0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pandas <=0.17
    - wqio 0.3.2
    - pybmpdb
    - pynsqd
    - pyodbc
    - openpyxl
    - xlrd

  run:
    - python
    - pandas <=0.17
    - wqio 0.3.2
    - pybmpdb
    - pynsqd
    - pyodbc
    - six
    - openpyxl
    - xlrd

test:
  imports:
    - pycvc

  commands:
    - python -c "import matplotlib as mpl; mpl.use('agg'); import pycvc; pycvc.test()"

  requires:
    - nose

about:
  home: https://github.com/Geosyntec/pycvc.git
  license:  BSD License
  summary: 'Connector for the Credit Valley Convservation Authority to wqio'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
